namespace TensileTestingApp.Services;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using TensileTestingApp.Services.Abstractions;
using TensileTestingApp.Services.Implementations;

public class PdfExportService
{
    private readonly ILogger _logger;

    public PdfExportService(ILogger logger)
    {
        _logger = logger;
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportTestResultsToPdf(
        string outputPath,
        double elasticModulus,
        double yieldStrength,
        double ultimateStrength,
        List<(double Length, double Force)> dataPoints,
        string? testName = null,
        string? specimenType = null)
    {
        try
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.PageColor("#FFFFFF");

                    page.Content().Column(col =>
                    {
                        // Title
                        col.Item().Text("Tensile Test Report").FontSize(28).Bold().FontColor("#2F4F4F");
                        col.Item().PaddingBottom(12);

                        // Test metadata
                        col.Item().Column(inner =>
                        {
                            if (!string.IsNullOrEmpty(testName))
                                inner.Item().Text($"Test Name: {testName}").FontSize(11);
                            if (!string.IsNullOrEmpty(specimenType))
                                inner.Item().Text($"Specimen Type: {specimenType}").FontSize(11);
                            inner.Item().Text($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}").FontSize(11);
                        });
                        col.Item().PaddingBottom(12);

                        // Results section
                        col.Item().Text("Test Results").FontSize(16).Bold().FontColor("#2F4F4F");
                        col.Item().PaddingBottom(8);

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(1);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Background("#D3D3D3").Padding(8)
                                    .Text("Parameter").Bold();
                                header.Cell().Background("#D3D3D3").Padding(8)
                                    .Text("Value").Bold();
                            });

                            table.Cell().Padding(8).Text("Elastic Modulus (E)");
                            table.Cell().Padding(8).Text($"{elasticModulus:F2} MPa");

                            table.Cell().Padding(8).Text("Yield Strength (σ₀.₂)");
                            table.Cell().Padding(8).Text($"{yieldStrength:F2} MPa");

                            table.Cell().Padding(8).Text("Ultimate Strength (σmax)");
                            table.Cell().Padding(8).Text($"{ultimateStrength:F2} MPa");
                        });

                        col.Item().PaddingBottom(12);

                        // Chart data summary
                        if (dataPoints.Count > 0)
                        {
                            col.Item().Text("Data Summary").FontSize(14).Bold().FontColor("#2F4F4F");
                            col.Item().Text($"Total data points collected: {dataPoints.Count}").FontSize(11);

                            double maxForce = dataPoints.Max(p => p.Force);
                            double maxLength = dataPoints.Max(p => p.Length);
                            col.Item().Text($"Max Force: {maxForce:F3} kN").FontSize(11);
                            col.Item().Text($"Max Length: {maxLength:F3} mm").FontSize(11);
                        }

                        col.Item().PaddingBottom(8);
                        col.Item().LineHorizontal(1).LineColor("#D3D3D3");
                        col.Item().PaddingBottom(8);
                        col.Item().Text("Report generated by TensileTestingApp").FontSize(9).FontColor("#808080");
                    });
                });
            }).GeneratePdf(outputPath);

            _logger.LogInfo($"PDF report exported successfully to: {outputPath}");
        }
        catch (Exception ex)
        {
            _logger.LogError($"Failed to export PDF report: {ex.Message}", ex);
            throw;
        }
    }
}
