namespace TensileTestingApp.Services;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using TensileTestingApp.Services.Abstractions;
using TensileTestingApp.Services.Implementations;

public class PdfExportService
{
    private readonly ILogger _logger;

    public PdfExportService(ILogger logger)
    {
        _logger = logger;
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportTestResultsToPdf(
        string outputPath,
        double elasticModulus,
        double yieldStrength,
        double ultimateStrength,
        List<(double Length, double Force)> dataPoints,
        string? testName = null,
        string? specimenType = null)
    {
        try
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.PageColor("#FFFFFF");

                    page.Content().Column(col =>
                    {
                        // Title
                        col.Item().Text("Tensile Test Report").FontSize(28).Bold().FontColor("#2F4F4F");
                        col.Item().PaddingBottom(12);

                        // Test metadata
                        col.Item().Column(inner =>
                        {
                            if (!string.IsNullOrEmpty(testName))
                                inner.Item().Text($"Test Name: {testName}").FontSize(11);
                            if (!string.IsNullOrEmpty(specimenType))
                                inner.Item().Text($"Specimen Type: {specimenType}").FontSize(11);
                            inner.Item().Text($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}").FontSize(11);
                        });
                        col.Item().PaddingBottom(12);

                        // Results section
                        col.Item().Text("Test Results").FontSize(16).Bold().FontColor("#2F4F4F");
                        col.Item().PaddingBottom(8);

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(1);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Background("#D3D3D3").Padding(8)
                                    .Text("Parameter").Bold();
                                header.Cell().Background("#D3D3D3").Padding(8)
                                    .Text("Value").Bold();
                            });

                            table.Cell().Padding(8).Text("Elastic Modulus (E)");
                            table.Cell().Padding(8).Text($"{elasticModulus:F2} MPa");

                            table.Cell().Padding(8).Text("Yield Strength (σ₀.₂)");
                            table.Cell().Padding(8).Text($"{yieldStrength:F2} MPa");

                            table.Cell().Padding(8).Text("Ultimate Strength (σmax)");
                            table.Cell().Padding(8).Text($"{ultimateStrength:F2} MPa");
                        });

                        col.Item().PaddingBottom(12);

                        // Chart data summary
                        if (dataPoints.Count > 0)
                        {
                            col.Item().Text("Data Summary").FontSize(14).Bold().FontColor("#2F4F4F");
                            col.Item().Text($"Total data points collected: {dataPoints.Count}").FontSize(11);

                            double maxForce = dataPoints.Max(p => p.Force);
                            double maxLength = dataPoints.Max(p => p.Length);
                            col.Item().Text($"Max Force: {maxForce:F3} kN").FontSize(11);
                            col.Item().Text($"Max Length: {maxLength:F3} mm").FontSize(11);

                            col.Item().PaddingBottom(12);
                            col.Item().Text("Force vs Length Chart").FontSize(12).Bold().FontColor("#2F4F4F");
                            col.Item().PaddingBottom(8);
                            RenderForceVsLengthChart(col, dataPoints);
                        }

                        col.Item().PaddingBottom(8);
                        col.Item().LineHorizontal(1).LineColor("#D3D3D3");
                        col.Item().PaddingBottom(8);
                        col.Item().Text("Report generated by TensileTestingApp").FontSize(9).FontColor("#808080");
                    });
                });
            }).GeneratePdf(outputPath);

            _logger.LogInfo($"PDF report exported successfully to: {outputPath}");
        }
        catch (Exception ex)
        {
            _logger.LogError($"Failed to export PDF report: {ex.Message}", ex);
            throw;
        }
    }

    private static void RenderForceVsLengthChart(ColumnDescriptor col, List<(double Length, double Force)> dataPoints)
    {
        if (dataPoints.Count < 2)
        {
            col.Item().Text("Insufficient data for chart").FontSize(10).FontColor("#808080");
            return;
        }

        double minX = dataPoints.Min(p => p.Length);
        double maxX = dataPoints.Max(p => p.Length);
        double minY = dataPoints.Min(p => p.Force);
        double maxY = dataPoints.Max(p => p.Force);

        // Prevent division by zero
        if (Math.Abs(maxX - minX) < 0.0001 || Math.Abs(maxY - minY) < 0.0001)
        {
            col.Item().Text("Insufficient data range for chart").FontSize(10).FontColor("#808080");
            return;
        }

        // Create ASCII chart representation
        const int chartWidth = 80;
        const int chartHeight = 20;
        char[,] chart = new char[chartHeight, chartWidth];

        // Initialize chart with spaces
        for (int y = 0; y < chartHeight; y++)
        {
            for (int x = 0; x < chartWidth; x++)
            {
                chart[y, x] = ' ';
            }
        }

        // Draw axes
        for (int y = 0; y < chartHeight - 1; y++)
        {
            chart[y, 0] = '|';
        }
        for (int x = 0; x < chartWidth; x++)
        {
            chart[chartHeight - 1, x] = '-';
        }
        chart[chartHeight - 1, 0] = '+';

        // Plot data points
        foreach (var point in dataPoints)
        {
            int x = (int)((point.Length - minX) / (maxX - minX) * (chartWidth - 2)) + 1;
            int y = (int)((maxY - point.Force) / (maxY - minY) * (chartHeight - 2));

            if (x >= 1 && x < chartWidth && y >= 0 && y < chartHeight - 1)
            {
                chart[y, x] = '*';
            }
        }

        // Convert chart to string
        var chartLines = new List<string>();
        for (int y = 0; y < chartHeight; y++)
        {
            var line = "";
            for (int x = 0; x < chartWidth; x++)
            {
                line += chart[y, x];
            }
            chartLines.Add(line.TrimEnd());
        }

        // Add chart to PDF as monospace text
        col.Item().Text(string.Join("\n", chartLines))
            .FontSize(8)
            .FontColor("#000000")
            .FontFamily("Courier New");

        // Add axis labels
        col.Item().Row(row =>
        {
            row.RelativeItem().Text($"Length: {minX:F2} mm → {maxX:F2} mm").FontSize(9);
            row.RelativeItem().Text($"Force: {minY:F2} kN → {maxY:F2} kN").FontSize(9);
        });
    }
}
